#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def getTotalX(a, b):
    t= max(a)
    f=min(b)
    c=0
    l1=[]
    fl=0
    fl1=0
    for x in range(t,(f+1)):
        fl=0
        for i in a:
            if(x%i!=0):
                fl=1 
                break
        if(fl==0):
            l1.append(x)
    
    for i in l1:
        fl1=0
        for j in b:
            if(j%i!=0):
                fl1=1
                break
        if(fl1==0):
            c+=1
    return c
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()
