#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    # Write your code here
    a= list(path)
    b=[-1,0,1]
    conter=0
    v=0
    for i in range(steps):
        if (a[i]=='U'):
            conter+=1
        else:
            conter-=1
        if(conter==0 and i!=0):
            if(a[i]=='U'):
                v+=1 
    return v

            
                


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
