#!/bin/python3

import os
import sys

#
# Complete the pageCount function below.
#
def pageCount(n, p):
    front=1
    back=n
    turnf=0
    turnb=0
    if (p==front or p==back):
        return 0
    elif(n%2==1 and p==back-1):
        return 0
    else:
        while (p>front):
            front+=2
            turnf+=1
        while (p<back):
            if(n%2==1):
                if(p==back-1):
                    break
            back-=2
            turnb+=1
        return min(turnf,turnb)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
