#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the migratoryBirds function below.
def migratoryBirds(arr):
    x=max(arr)
    a=[]
    for i in range (0, x+1):
        a.append(0)
    for j in arr:
        a[j]+=1
    m=0
    typ=0
    for k in range (1,len(a)):
        if(m<a[k]):
            m=a[k]
            typ=k
        elif(m==a[k]):
            if(typ>k):
                typ=k
    return typ

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
